### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Goosie**
Change     cargo build --release into
    cargo build --all-features --release
Otherwise, it won't run.
Or explain when you use     cargo build --release and when you have to use 
    cargo build --all-features --release

### CODE REVIEW

**Review by dr-orlovsky — APPROVED** [review]

**Comment by zoedberg** [comment]
@dr-orlovsky IMO we should double-check this merged PR: haven't we fixed default build with #112?

I don't think that we should suggest users to build with `--all-features`, some features in the future could introduce vendored libs and usage of those should not be suggested

**Comment by dr-orlovsky** [comment]
Right, than `--features default` should work better

**Comment by zoedberg** [comment]
I don't think we need to make the `--features default` flag explicit, it's already the default behavior

From the [official documentation](https://doc.rust-lang.org/cargo/commands/cargo-build.html#feature-selection):

> When no feature options are given, the default feature is activated for every selected package.

So I think we just need to revert this PR

**Comment by dr-orlovsky** [comment]
Reverted with https://github.com/LNP-BP/rgb-node/commit/77ca128073c114db0fc7fbbd4a241dfd3b7d5c76

**Pull request merged**
