### PR TITLE
Electrum resolver

### PR DESCRIPTION
**Pull request by afilini**
Built on top of #12

### CODE REVIEW

**Comment by afilini** [comment]
Also uses changes from lnp-bp/rust-lnpbp#50, so we should consider merging that one first

**Comment by dr-orlovsky** [comment]
> Also uses changes from LNP-BP/rust-lnpbp#50, so we should consider merging that one first

Merged. Can you pls re-base so it will be easier to see specific changes by this PR?

**Comment by afilini** [comment]
Rebased now

**Comment by dr-orlovsky** [comment]
Is this PR ready for review? Can’t merge the otter one in rust-lnpbp w/o it

**Comment by afilini** [comment]
I didn't want to merge this one with references to my personal rust-lnpbp repo, so I thought you wanted to merge the other one first and update the reference here. 

But other than that yes, it should be ready

**Comment by dr-orlovsky** [comment]
The other PR is merged so you can update the dependency link and I will merge this one

**Comment by dr-orlovsky** [comment]
Don't worry, has done it with https://github.com/LNP-BP/rgb-node/pull/31

**Pull request merged**
